// <auto-generated />
using FinancialControl.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialControl.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinancialControl.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Finalidade")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descricao = "Alimentação",
                            Finalidade = 1
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descricao = "Salário",
                            Finalidade = 2
                        },
                        new
                        {
                            CategoriaId = 3,
                            Descricao = "Geral",
                            Finalidade = 3
                        });
                });

            modelBuilder.Entity("FinancialControl.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PessoaId"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas", (string)null);

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            Idade = 30,
                            Nome = "Paulo"
                        },
                        new
                        {
                            PessoaId = 2,
                            Idade = 16,
                            Nome = "Ana"
                        });
                });

            modelBuilder.Entity("FinancialControl.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransacaoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransacao")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransacaoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Transacoes", (string)null);

                    b.HasData(
                        new
                        {
                            TransacaoId = 1,
                            CategoriaId = 1,
                            Descricao = "Supermercado",
                            PessoaId = 1,
                            TipoTransacao = 1,
                            Valor = 150.99m
                        },
                        new
                        {
                            TransacaoId = 2,
                            CategoriaId = 2,
                            Descricao = "Pagamento Mensal",
                            PessoaId = 1,
                            TipoTransacao = 2,
                            Valor = 3000.00m
                        },
                        new
                        {
                            TransacaoId = 3,
                            CategoriaId = 3,
                            Descricao = "Lanche na escola",
                            PessoaId = 2,
                            TipoTransacao = 1,
                            Valor = 15.50m
                        });
                });

            modelBuilder.Entity("FinancialControl.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("FinancialControl.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancialControl.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Transacoes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("FinancialControl.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinancialControl.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
